server:
  port: 9000
spring:
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://fpfos.com/fpfos-thesis?characterEncoding=utf-8
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: fpfos.com
    port: 6379
